### ISSUE TITLE
Fix the config file

### ISSUE THREAD

**Issue by hrishiballal** [apache/couchdb-pkg#10]
When I updated to Couchdb 2.1.1 the installation failed and bricked my existing box. The culprit is typos in teh config file (atleast according to apt-get): 
https://github.com/apache/couchdb-pkg/blob/master/debian/couchdb.config#L78
https://github.com/apache/couchdb-pkg/blob/master/debian/couchdb.config#L86

"whitespace" is misspelt, I am not sure how to resurrect my production install but I hope that this is caught in testing the next time.

**Comment by wohali** [comment]
Thanks for the report! This has been in the config file since day 1 - and didn't get caught in testing.

We'll get new packages posted in a few hours

**Comment by hrishiballal** [comment]
Thanks for this, strange that apt caught it just now. Basically I installed Couchdb 2.1 earlier and it worked fine when I used apt-get upgrade to upgrade to 2.1.1, apt bombed giving this error. I look forward to the fixes and testing it. . 

Thank you again for all the work with couch! Really appreciate it.

**Comment by wohali** [comment]
New packages being built and should be visible on bintray within 1 hour.

Sorry for the inconvenience.

**Comment by wohali** [comment]
2.1.1-1 packages uploaded and published. Thank you again for bringing this to our attention! :)
