### ISSUE TITLE
.deb packages for s390x cpu on Ubuntu jammy and lunar

### ISSUE THREAD

**Issue by kun-lu20** [apache/couchdb-pkg#108]
Since s390x .deb package for Ubuntu focal has already been available (https://apache.jfrog.io/artifactory/couchdb-deb/pool/C/CouchDB/couchdb_3.3.2~focal_s390x.deb), could the community also consider to release s390x .deb packages on Ubuntu jammy and lunar? Thanks!

## Expected Behavior

Release CouchDB s390x .deb packages on Ubuntu jammy and lunar.

## Current Behavior

s390x .deb package is already available for Ubuntu focal since v3.3.2.

## Possible Solution

Build s390x .deb package via qemu.

## Your Environment

* Version used: v3.3.2
* Browser Name and version:
* Operating System and version (desktop or mobile): Ubuntu jammy and Ubuntu lunar
* Link to your project:

**Comment by nickva** [comment]
@kun-lu20 focal would make sense to have for multiple architectures. But lunar is not an lts release, we probably won't be making a package for that. 

Also, as a reminder, packages are provided as a courtesy. The official release artifact is the source release.

**Comment by kun-lu20** [comment]
Hi @nickva ,

> @kun-lu20 focal would make sense to have for multiple architectures. But lunar is not an lts release, we probably won't be making a package for that.

Thanks for letting me know. Yes, providing packages for LTS release makes sense. 

> Also, as a reminder, packages are provided as a courtesy. The official release artifact is the source release.

Got it. Thanks again for providing the convenience packages.

**Comment by nickva** [comment]
A multiarch ubuntu jammy image was uploaded to couhdb-ci https://hub.docker.com/layers/apache/couchdbci-ubuntu/jammy-erlang-24.3.4.10/images/sha256-865af831bf8cd925b95d64fb50f32048f024327d1c57a7c2546793a45ea2bcfe?context=repo

**Comment by big-r81** [comment]
Closing this as resolved for now.
