### ISSUE TITLE
Debian Bookworm packages please

### ISSUE THREAD

**Issue by PeteLawler** [apache/couchdb-pkg#112]
## Expected Behavior
Install CouchDB as per instructions without error.

## Current Behavior
An error is thrown as there are no Bookworm packages.

## Possible Solution
Create Bookworm packages.

## Steps to Reproduce (for bugs)
1. Install Debian Bookworm
2. Follow installation instructions for CouchDB on Debian.

## Context
My project has moved over to Debian Bookworm release. I have to maintain a system of Debian Bullseyes to keep CouchDB operating without needing magic sauce for installation. Instead I have to special case the underlying project OS.

**Comment by nickva** [comment]
There seems to be an included [libmozjs-78](https://packages.debian.org/bookworm/libmozjs-78-0) package so it should be doable.

**Comment by nickva** [comment]
Bookworm packages are now available in the Apache CouchDB .deb repo

So far it's for x86_64 arch only.
