### ISSUE TITLE
path to certificates

### ISSUE THREAD

**Issue by alfille** [apache/couchdb-pkg#113]
I'm using Debian 12 and snap couchdb

What path do I use for "cert_file" in [ssl] ?

To be more specific:

I know where my cert and key files are (installed by Caddy) and I can certainly move or link them to anywhere in the filesystem. But it seems that snap-couchdb has a different view of the filesystem than I do. I've tried many permutations but consistently get enoent.

**Comment by sklassen** [comment]
Any user-defined (editable) files need to be stored within `/var/snap/couchdb/current/`. 

If you need to debug further, there should be a couchdb.remsh script. You can use the erlang file library to confirm that couchdb can read the files.
