### ISSUE TITLE
Couchdb Snap package stuck at couchdb 3.1.1

### ISSUE THREAD

**Issue by sblaisot** [apache/couchdb-pkg#114]
## Expected Behavior

Installing couchdb through snap packages following instructions at https://docs.couchdb.org/en/stable/install/snap.html install latest  couchdb version (currently 3.3.2)

## Current Behavior

Current latest snap package install CouchDB 3.1.1 and has not been updated in https://snapcraft.io/couchdb for two and a half years

## Possible Solution

Build and publish updated snap package for couchdb 3.3.2

## Steps to Reproduce (for bugs)
1. starting from a fresh Debian 12 system
2. `apt install snapd`
3. `snap install core`
4. `snap install couchdb`
5. `snap set couchdb admin=StrongAdminPassw0rd`
6. `snap start couchdb`
7. `curl http://127.0.0.1:5984/
{"couchdb":"Welcome","version":"3.2.1","git_sha":"244d428af","uuid":"f7b83554fa2eb43778963d18a1f92211","features":["access-ready","partitioned","pluggable-storage-engines","reshard","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}`

## Context

I was trying to install couchdb as a snap package on Debian 12 as there is currently no deb package for this version.

## Your Environment

Debian 12, trying to install CouchDB 3.3.2

**Comment by sblaisot** [comment]
If you don't plan to publish updated snap package, at least the documentation should mention snap packages are deprecated.

**Comment by rnewson** [comment]
+1 to remove snap-related docs
