### ISSUE TITLE
Use Snapd Native Configuration

### ISSUE THREAD

**Issue by ryanjyoder** [apache/couchdb-pkg#13]
# Use Snapd Native Configuration

## Expected Behavior
Couchdb should take advantage of snaps native configuration management. This is the expected behavior when installing a snap.

## Current Behavior
Currently to configure the couchdb snap the user needs to edit /var/snap/couchdb/current/local.ini 

## Possible Solution
It's seems possible to read the configuration in `rel/couchdb/bin/snap_run` and write them to a file before the exec is done.

## Context

This is just a nice to have. Editing the local.ini works.

**Comment by wohali** [comment]
PRs welcome.

**Comment by wohali** [comment]
The snap package is unmaintained at present. We're asking for assistance from anyone who would like to contribute.

**Comment by wohali** [comment]
The outdated 2.0.0 unsupported CouchDB snap package has been unpublished.
