### ISSUE TITLE
[Debian/Ubuntu] Set n=1 for single node setups and/or use _cluster_setup endpoint

### ISSUE THREAD

**Issue by janl** [apache/couchdb-pkg#15]
https://github.com/apache/couchdb-setup/blob/master/src/setup.erl#L172-L174

**Comment by wohali** [comment]
I can only do this for Debian, where we configure in a postinst. rpm doesn't have a suitable configuration mechanism for this.

**Comment by janl** [comment]
for RPM, could we patch local.ini?

**Comment by wohali** [comment]
for RPM we can't know if it's standalone or clustered at all at install time, there's no mechanism to prompt the user ask them. So we punt on any sort of configuration :(

**Comment by janl** [comment]
ah ok, then it’s all fine, if we send them to fauxton for setup

**Comment by wohali** [comment]
Which we do [in the docs](http://docs.couchdb.org/en/2.1.1/install/unix.html#installing-the-apache-couchdb-packages)

> Debian/Ubuntu installs from binaries will be pre-configured for single node or clustered installations. For clusters, multiple nodes will still need to be joined together; follow the Cluster Setup Wizard steps to complete the process.

I'll make sure this happens for Debian, though. Good catch.
