### ISSUE TITLE
Missing Hex dependency

### ISSUE THREAD

**Issue by martiell** [apache/couchdb-pkg#152]
Building deb packages from source tarball for Ubuntu Jammy fails when using containers to build.

## Expected Behavior
I have built a source tarball based on the main branch, and am trying to build Debian packages as follows:

```
CONTAINERARCH=arm64 ./build.sh couch ubuntu-jammy apache-couchdb-3.4.0-d5ce026-RC3.tar.gz
```

This used to complete successfully and create the expected .deb packages.

## Current Behavior
The build fails with the following error:

```
==> apache-couchdb-3.4.0-d5ce026 (clean)
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell) or set the ELIXIR_ERL_OPTIONS="+fnu" environment variable
Mix requires the Hex package manager to fetch dependencies
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] ** (Mix) Could not find an SCM for dependency :junit_formatter from CouchDBTest.Mixfile
make[3]: *** [Makefile:470: clean] Error 1
```

## Possible Solution
As a workaround, I am using the following change in debian/rules. The command is suggested by the error message.
```
 override_dh_auto_clean:
+       mix local.hex --force
```

I'm not familiar enough with the build to know what should be providing "hex".

## Steps to Reproduce (for bugs)
1. Create a source tarball using `make dist`
2. Copy the resulting tarball into the couchdb-pkg directory
3. Run `CONTAINERARCH=arm64 ./build.sh couch ubuntu-jammy apache-couchdb-3.4.0-d5ce026-RC3.tar.gz` or similar to try to build packages from the tarball.

## Context
I'm trying to build Debian packages in order to test the forthcoming Nouveau feature.

## Your Environment
* Version used:
  * couch @ d5ce0267a5b268388b68bf0b7bd5f50c951dd12c
  * couch-pkg @ 527fbeb89a935ec52836d8a0d7105ad1f8a46f88
* Browser Name and version: n/a
* Operating System and version (desktop or mobile): Ubuntu Jammy
* Link to your project: n/a

**Comment by big-r81** [comment]
Does [this](https://github.com/apache/couchdb/pull/5250) solve your problem?

**Comment by martiell** [comment]
Yes, thanks.
