### ISSUE TITLE
Can't create views on Ubuntu 17.10

### ISSUE THREAD

**Issue by lawrencengan** [apache/couchdb-pkg#17]
I have done a snap install of couchdb 2.0.0 (sudo snap install couchdb).  After installation, the verify fails on the "Create View" step saying "OS process timed out".  I cannot create any view document in any test database too.

I have read "Can't create views on Ubuntu #6" and executed the following commands and still cannot resolve the problem.

sudo service apparmor stop
sudo update-rc.d -f apparmor remove
sudo apt-get remove apparmor apparmor-utils
sudo apt-get install snapd

## Expected Behavior

Verify should complete successfully and I should be able to create view.

## Current Behavior

![image](https://user-images.githubusercontent.com/33790527/34527173-b89e26cc-f072-11e7-99ce-a888f0751fb9.png)

## Steps to Reproduce (for bugs)

1.sudo snap install couchdb
2.sudo service apparmor stop
3.sudo update-rc.d -f apparmor remove
4.sudo apt-get remove apparmor apparmor-utils
5.sudo apt-get install snapd
6.sudo snap remove couchdb
7.sudo snap install couchdb

## Your Environment

* Version used: Fauxton on Apache CouchDB v. 2.0.0
* Browser Name and version: Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Operating System and version (desktop or mobile):Ubuntu 17.10
* Link to your project:

**Comment by wohali** [comment]
No one is currently maintaining the snap package. If you have any idea how to help with this, we'd appreciate it.

**Comment by wohali** [comment]
Closed by #27.
