### ISSUE TITLE
Empty debian binary-i386 packages

### ISSUE THREAD

**Issue by lune** [apache/couchdb-pkg#20]
Not sure, if this is the right place to submit the issue, please let me know otherwise.
Unable to install coucbdb using the steps listed at http://docs.couchdb.org/en/master/install/unix.html on Ubuntu Xenial.
Is this due to **empty** packages at https://apache.bintray.com/couchdb-deb/ for xenial (i386)?

## Current Behavior

```bash
$ curl --head https://apache.bintray.com/couchdb-deb/dists/xenial/main/binary-i386/Packages
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 05 Mar 2018 19:01:05 GMT
Content-Type: inode/x-empty
Content-Length: 0
Connection: keep-alive
Last-Modified: Thu, 09 Nov 2017 18:25:00 GMT
Accept-Ranges: none
ETag: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Checksum-Sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
X-Checksum-Sha2: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

Where as for amd64 arch for xenial
```bash
curl --head https://apache.bintray.com/couchdb-deb/dists/stretch/main/binary-amd64/Packages
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 05 Mar 2018 19:01:30 GMT
Content-Type: text/plain
Content-Length: 2665
Connection: keep-alive
Last-Modified: Thu, 09 Nov 2017 18:24:58 GMT
Accept-Ranges: none
ETag: 7b263cc00dfc11f2f7afd05395b1bf02dba6d3134edeb4e89504357c17871b1f
X-Checksum-Sha1: 9b99b569c77ff387b53cb06277e5596e9ccbe4fe
X-Checksum-Sha2: 7b263cc00dfc11f2f7afd05395b1bf02dba6d3134edeb4e89504357c17871b1f
```
This is the same for all the other dists.

## Your Environment

* Version used: Ubuntu 16.04 Xenial
* Operating System and version (desktop or mobile): VirtualBox on OSX El Capitan

**Comment by wohali** [comment]
Apache CouchDB is not building 32-bit convenience packages, and does not intend to do so in the future.

You may be able to build your own 32-bit packages using the files in this repository if you so desire.
