### ISSUE TITLE
Initscript (Ubuntu/debian) does not stop process

### ISSUE THREAD

**Issue by gnujeremie** [apache/couchdb-pkg#22]
## Expected Behavior
Running ```/etc/init.d/couchdb stop``` should stop couchdb process.

## Current Behavior
running ```/etc/init.d/couchdb stop``` does not stop couchdb. If I remove the ```--quiet``` option in the stop/start script, I get ```No process in pidfile '14888' found running; none killed```

## Your Environment

* Version used: 2.1.1
* Browser Name and version:
* Operating System and version (desktop or mobile): Ubuntu 14.10
* Link to your project:

**Comment by wohali** [comment]
Thanks for the report! Can you confirm that you installed packages from our repository?

**Comment by gnujeremie** [comment]
Yes i did, i followed instructions on couchdb website and my init.d script is the same as the one of this repo (I'm not on my computer i can't remember and check the name of the file)

Le 11 juin 2018 18:24:21 GMT+02:00, Joan Touzet <notifications@github.com> a écrit :
>Thanks for the report! Can you confirm that you installed packages from
>our repository?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/apache/couchdb-pkg/issues/22#issuecomment-396302384

-- 
Jérémie

**Comment by wohali** [comment]
Thanks @gnujeremie , we'll have a look.

**Comment by wohali** [comment]
Hi @gnujeremie , this issue is now resolved. We'll have new packages published shortly; until then, you can just copy the updated script or changes to your local copy. See: https://github.com/apache/couchdb-pkg/commit/415263d8c682d5eb0adbcdbc7c615c052f064848 for the details.

Thanks again for reporting this bug!

**Comment by gnujeremie** [comment]
Hi thanks, it seems to fix it. However, I still have one process running after I stop couchdb : 

```
# ps aux | grep couch
couchdb  28203  0.0  0.0   7500   312 ?        S    08:53   0:00 /opt/couchdb/bin/../erts-7.3/bin/epmd -daemon
root     28329  0.0  0.0  12252   928 pts/3    S+   08:54   0:00 grep --color=auto couch
```

When couchdb is running I have : 
```
# ps aux | grep couch
couchdb  28203  0.0  0.0   7500   312 ?        S    08:53   0:00 /opt/couchdb/bin/../erts-7.3/bin/epmd -daemon
couchdb  28341  8.1  0.4 1922912 139576 ?      Sl   08:54   0:10 /opt/couchdb/bin/../erts-7.3/bin/beam.smp -K true -A 16 -Bd -- -root /opt/couchdb/bin/.. -progname couchdb -- -home /home/couchdb -- -boot /opt/couchdb/bin/../releases/2.1.1/couchdb -name couchdb@127.0.0.1 -setcookie monster -kernel error_logger silent -sasl sasl_error_logger false -noshell -noinput -config /opt/couchdb/bin/../releases/2.1.1/sys.config
couchdb  28378  0.0  0.0  12912  1212 ?        Ss   08:54   0:00 sh -s disksup
couchdb  28379  0.0  0.0   4328   604 ?        Ss   08:54   0:00 /opt/couchdb/bin/../lib/os_mon-2.4/priv/bin/memsup
couchdb  28380  0.0  0.0   4328   348 ?        Ss   08:54   0:00 /opt/couchdb/bin/../lib/os_mon-2.4/priv/bin/cpu_sup
root     28537  0.0  0.0  12252   932 pts/3    S+   08:56   0:00 grep --color=auto couch
```

**Comment by wohali** [comment]
Right, epmd isn't specifically couch, and can be used by many Erlang processes. We intentionally don't stop it because other services on the box may be dependent on it.

**Comment by gnujeremie** [comment]
Oh, right now I kill it manually but it means I can keep it alive ? the couchdb user running the process made me think it was specific to couchdb.

**Comment by wohali** [comment]
Yes, you can leave it if you want, it's not critical. The couchdb user starts it if it's not already started by the OS, or another user, for other purposes. (An example would be rabbitmq.)

**Comment by gnujeremie** [comment]
Ok thanks a lot for the input 👍
