### ISSUE TITLE
Included `rebar` binary contains bug rendering failed builds on ARM64

### ISSUE THREAD

**Issue by lag-linaro** [apache/couchdb-pkg#24]
**couchdb-pkg [master]$ make build-couch $(lsb_release -cs) PLATFORM=$(lsb_release -cs)**

```
cd ../couchdb && make dist
make[1]: Entering directory '/home/linaro/projects/docker-hub/couchdb'
==> config (compile)
Compiled src/config_sup.erl
Compiled src/config_notifier.erl
Compiled src/config_util.erl
Compiled src/config_listener.erl
Compiled src/config_writer.erl
Compiled src/config_app.erl
Compiled src/config_listener_mon.erl
Compiled src/config.erl
==> b64url (compile)
Compiled src/b64url.erl
Compiling /home/linaro/projects/docker-hub/couchdb/src/b64url/c_src/b64url.c
cc: error: unrecognized command line option ‘-m64’
ERROR: compile failed while processing /home/linaro/projects/docker-hub/couchdb/src/b64url: rebar_abort
Makefile:81: recipe for target 'couch' failed
make[1]: *** [couch] Error 1
make[1]: Leaving directory '/home/linaro/projects/docker-hub/couchdb'
Makefile:87: recipe for target 'build-couch' failed
make: *** [build-couch] Error 2
```

Pulling newer binary from [HERE](https://github.com/rebar/rebar/wiki/rebar) fixed the issue.

**Comment by wohali** [comment]
The ASF requires building from source for all dependencies, so we can't merge a change to build from an external binary instead.

We have a [patched rebar (2)](https://github.com/apache/couchdb-rebar/tree/2.6.0-couchdb) that we ship. This is downloaded and build from the Apache repostiroy.

If you are proposing an update to the latest rebar (2) from https://github.com/rebar/rebar that will need to be pulled into https://github.com/apache/couchdb-rebar and merged with our patch.

I will close this issue and file a new one on apache/couchdb for this work.

**Comment by wohali** [comment]
FYI note there are other build issues on ARM64 that require more than just build chain work, see https://github.com/apache/couchdb/issues/892#issuecomment-338030413 for the details. You will need a `libmozjs185` built in **32-bit mode**.
