### ISSUE TITLE
RPM CouchDB init script always returns 0 for status

### ISSUE THREAD

**Issue by sebastien-prudhomme** [apache/couchdb-pkg#28]
## Expected Behavior
If CouchDB is not running, /etc/rc.d/init.d/couchdb status should return value other than 0

## Current Behavior
If CouchDB is not running, /etc/rc.d/init.d/couchdb status returns 0

## Possible Solution
In the "status" case of /etc/rc.d/init.d/couchdb, exit with the value returned by the status() function

**Comment by sebastien-prudhomme** [comment]
Seems that all command are broken, "stop", "start", etc should exit with the $retval. Debian package is also broker.

**Comment by sebastien-prudhomme** [comment]
Replacing the ending "exit 0" with "exist $?" can resolve the problem.

**Comment by wohali** [comment]
Thanks @sebastien-prudhomme , would you like to submit a PR with this change? The change will then make it into the next release of CouchDB (2.3.0).

Thank you for your contribution and bug report for CouchDB! :confetti_ball:
