### ISSUE TITLE
Error making couchdb 2.3.0 with Erlang 21.1.4

### ISSUE THREAD

**Issue by rolfn** [apache/couchdb-pkg#41]
## Expected Behavior

`make release` should not end with an error.

## Current Behavior

* `make release`
```
...
==> rel (generate)
=ERROR REPORT==== 26-Sep-1951::01:00:53.****** ===
File operation error: eacces. Target: /usr/lib64/erlang/lib/crypto-4.3.3/priv/obj/stw17j4b. Function: get_file.
ERROR: Failed to generate target from spec: "copy file /usr/lib64/erlang/lib/crypto-4.3.3/priv/obj/stw17j4b -> /home/niepra01/myapp/couchdb/apache-couchdb-2.3.0/rel/couchdb/lib/crypto-4.3.3/priv/obj/stw17j4b: no such file or directory\n"
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /home/niepra01/myapp/couchdb/apache-couchdb-2.3.0/rel: rebar_abort
make: *** [Makefile:348: release] Fehler 1
```
The file `/usr/lib64/erlang/lib/crypto-4.3.3/priv/obj/stw17j4b` exist on my system as part of "erlang-21.1.4" , but has zero length.

## Possible Solution
???

## Steps to Reproduce (for bugs)

1. Get the source file: `apache-couchdb-2.3.0.tar.gz`
1. `tar xvzf apache-couchdb-2.3.0.tar.gz`
1. `cd apache-couchdb-2.3.0/`
1. `./configure`
1. `make release`

## Your Environment

* Version used: 2.3.0
* Operating System and version (desktop or mobile): openSUSE Tumbleweed (20181211)
* Erlang: Erlang/OTP 21 [erts-10.1.3]

How can I fix the problem? On an older system (Erlang 18) creation of couchdb binaries was successful.

**Comment by wohali** [comment]
Your error says:

`File operation error: eacces`

rebar was unable to access one of the required source files.

Check read permissions of all files in your Erlang source directory (under the `/usr/lib64` path).
