### ISSUE TITLE
Snap package is not available in the Snap Store

### ISSUE THREAD

**Issue by rominf** [apache/couchdb-pkg#42]
Snap package is not available in the Snap Store.

## Expected Behavior

Snap package should be available in the Snap Store, as described in the [documentation](http://docs.couchdb.org/en/stable/install/snap.html).

## Current Behavior

![Snap Store screenshot](https://user-images.githubusercontent.com/3449635/50775183-85319100-12a6-11e9-956f-ac294a5ac853.png)
```shell
$ sudo snap install couchdb
error: snap "couchdb" not found
```

## Possible Solution

Upload `couchdb` snap again.

## Steps to Reproduce (for bugs)

1. Go to https://snapcraft.io/search?category=&q=couchdb

OR

1. Type in the terminal:
```shell
$ sudo snap install couchdb
```

## Context

Installation through `snap` is the easiest way to run `couchdb` on some GNU/Linux distributions.

## Your Environment

Irrelevant. This is not because of my environment.

**Comment by wohali** [comment]
We're still testing the snap before releasing it.

**Comment by rominf** [comment]
Nice to hear this. Meantime I'm using Docker image and happy with it. Hope you will release it soon!

**Comment by danielfoxp2** [comment]
The issue still exists 6 months later. I was following the instalation guide from CouchDB docs when I faced this problem. If it is still not ready for production why the docs are endorsing this way of installment?

**Comment by wohali** [comment]
Dealing with this today. Sorry for the delay.

**Comment by wohali** [comment]
The snap package has been submitted. This unfortunately requires human review:

```
  - (NEEDS REVIEW) 'daemon' should not be used with 'browser-support'
```

It'll have to wait until a human at Ubuntu approves it, or someone suggests a workaround.

**Comment by wohali** [comment]
The package is now live. Enjoy!

**Comment by wohali** [comment]
@ryanjyoder ^^^ and specifically https://github.com/apache/couchdb-pkg/pull/50 might make you happy ;)
