### ISSUE TITLE
Couchdb for aarch64

### ISSUE THREAD

**Issue by zhongtianxie** [apache/couchdb-pkg#43]
where i can find aarch64 package or build it by myself.

**Comment by zhongtianxie** [comment]
Hi Devs:
    can anyone provide a src.rpm

**Comment by wohali** [comment]
Packages for debian stretch are coming, as is a Docker container. We have no plans to provide aarch64 packages on any other platform at this time.

The spec file for the RPM is in this repo and you can find the top-level Makefile that is used to build it, using the officially released tarball from https://couchdb.apache.org/. We do not build srpms.
