### ISSUE TITLE
Cannot upgrade couchdb 2.3.0 to 2.3.1 on Ubuntu~xenial

### ISSUE THREAD

**Issue by suculent** [apache/couchdb-pkg#44]
## Expected Behavior
I would expect `apt install couchdb` to upgrade my 2.3.0 to 2.3.1 seamlessly, however dpkg fails to me.

## Current Behavior

Having `/var/lib/dpkg/info/couchdb.postinst` starting with `#!/bin/sh -x`:
```
Setting up couchdb (2.3.1~xenial) ...
+ set -e
+ . /usr/share/debconf/confmodule
+ [ !  ]
+ PERL_DL_NONLAZY=1
+ export PERL_DL_NONLAZY
+ [  ]
+ exec /usr/share/debconf/frontend /var/lib/dpkg/info/couchdb.postinst configure 2.1.1-1~xenial
dpkg: error processing package couchdb (--configure):
 subprocess installed post-installation script returned error exit status 128
Errors were encountered while processing:
 couchdb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

When running the offending command manually:

```
# exec /usr/share/debconf/frontend /var/lib/dpkg/info/couchdb.postinst configure 2.1.1-1~xenial
```

The SSH connection I've used to issue the command gets terminated.

## Possible Solution
What I don't get is why the debconf/frontend executes postinst with "2.1.1-1~xenial" which is current version, not the one being installed.

## Steps to Reproduce (for bugs)
Using this tutorial http://docs.couchdb.org/en/latest/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages to install binary package on Ubuntu 18.

## Context
Just trying to upgrade 2.3.0 to 2.3.1 to get rid of path traversal vulnerability.

## Your Environment
* Version used: 2.3.0/2.3.1
* Browser Name and version: n/a
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS Xenual ```Linux 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux```
* Link to your project: https://github.com/suculent/thinx-device-api

**Comment by wohali** [comment]
This suggests that you have `2.1.1-1` installed, not `2.3.0`. We haven't done extensive testing on upgrading from older versions to the latest; there may well be a bug there, but this is the first report.

That argument seems correct, see https://wiki.debian.org/MaintainerScripts for the flow of what happens when you upgrade.

It is safe to do `apt uninstall couchdb && apt install couchdb` to upgrade as well, if you prefer.

I can dig into this if you need to, but if you can, try the above workaround first? Thanks.

**Comment by wohali** [comment]
No response from requestor; closing for now. If anyone else runs into this, please say so and I'll re-open the issue.

**Comment by mm0ntg0m** [comment]
Seems we are experiencing a similar error

apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Setting up couchdb (2.3.1~stretch) ...
dpkg: error processing package couchdb (--configure):
 subprocess installed post-installation script returned error exit status 128
Errors were encountered while processing:
 couchdb
E: Sub-process /usr/bin/dpkg returned an error code (1)

2.3.1 appears to be installed and running. When we run curl localhost:5984, we get...
{"couchdb":"Welcome","version":"2.3.1","git_sha":"c298091a4","uuid":"c89c514e09cd4f0491144e72c614af91","features":["pluggable-storage-engines","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}

We attempted your suggestion of removing and reinstalling couchdb. It did not change the result.

Is this a situation where the 2.3.0 installer left a mess and the 2.3.1 installer can't clean it up?
