### ISSUE TITLE
Add support for Debian 10 (buster)

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-pkg#47]
Should be straightforward. Same approach as #8 , but the automation scripting needs to be updated.

Also need support over in apache/couchdb-ci.

**Comment by adrian-the-git** [comment]
Curious @wohali whether you've yet attempted this build, perhaps using the debian target with the PLATFORM variable. I will need to do this in a couple of days and I'm wondering whether I should prepare for an autotools deep dive.

**Comment by wohali** [comment]
It's a mechanical thing and hope to get to it this week, sorry for the delay.

CouchDB hasn't used autotools since 1.x.

**Comment by adrian-the-git** [comment]
Excellent! Fewer AC_HEADACHES for me.

**Comment by fredrikjonson** [comment]
@wohali Any update on this issue? 

I've tried to build packages for buster locally with the following patch, and after some cargo culting, the resulting couchdb package was installable and ran.

[couchdb-pkg-buster.patch.txt](https://github.com/apache/couchdb-pkg/files/3530156/couchdb-pkg-buster.patch.txt)

**Comment by wohali** [comment]
@fredrikjonson Yup, all good, thanks for the confirmation. I'm just cleaning up some of the `lintian` stuff now.

I've already published the `js-1.8.5` packages for Buster. CouchDB should follow later today.

**Comment by wohali** [comment]
Packages are pushed and live, enjoy!

**Comment by wohali** [comment]
There was a problem installing the package on buster if you'd never installed CouchDB before (say, prior to upgrading to Buster). This has been fixed and pushed over the old package (no new -version number), so if you find yourself unable to install CouchDB on buster, do:

```
apt clean
apt update
apt install couchdb
```

Sorry about that.

**Comment by adrian-the-git** [comment]
Thanks for this. 

I had trouble starting the couchdb service on a fresh Debian 10 with no prior couch installs because the files in /opt/couchdb/etc/default.d/ were owned root:root and mode 0640 (unreadable by user or group couchdb). I solved this with `chown -R couchdb:couchdb /opt/couchdb/etc` in the debian/couchdb.postinst file. Perhaps root:couchdb is a better choice for the default.d subdirectory, however.

**Comment by wohali** [comment]
Thanks, this is a definite bug and I'll spin new buster packages Monday. Reopening so I don't lose track.

**Comment by wohali** [comment]
New packages pushed and tested.
