### ISSUE TITLE
Add support for non-LTS Ubuntu releases

### ISSUE THREAD

**Issue by wohali** [apache/couchdb-pkg#48]
Migrated from https://github.com/apache/couchdb/issues/2119 :

> Release packages for Ubuntu 18.10 / 19.04, current 18.04 can't be used anymore as libcurl3 conflicts with libcurl4, which is a dependency of curl so you have to resort to unofficial snap builds

> Having to resort to LTS versions just because of the DB engine is problematic for me, as I have to keep my applications current with the latest versions of Linux

@wohali 's response:

> Current policy is only to support LTS builds. The reason is that CouchDB does not coexist well on machines running other processes, and since you need a dedicated server for that machine, you might as well run an LTS release.

> We are a volunteer run project with limited computing resources. Running a full regression test and build on each new platform requires a large amount of infrastructure on our side, plus min. 1 hour of compute time per platform.

> Adding non-LTS support is not likely in the near future, but we'll consider it.

**Comment by vlad88sv** [comment]
Thanks a lot for your response, I'm talking about a development environment so I don't find convenient to have a local VM just for CouchDB but it's what it's! sounds like that would be the best approach, or Docker probably.

Thank you for your time and hard work on this amazing project!

**Comment by sklassen** [comment]
You could try 'snap install couchdb-sklassen' it uses libcurl3 but it is
within a sandboxed environment where it doesn't interfere with the standard
installation.

I'd appreciate any feedback on performance.

**Comment by wohali** [comment]
We now have the full snap package deployed, so it's just `snap install couchdb` now. Documentation is here:  https://github.com/apache/couchdb-pkg/blob/master/README-SNAP.md  Big thanks to @sklassen who helped make this a reality! 🎆 🍾 

We also just deployed Debian buster packages, which might work OK under 19.xx since they are built against libcurl4. Give those a go if you want, follow the standard install docs but specify "buster" as your distro.

Since we're not planning on supporting non-LTS releases at this time, I'm going to close this ticket.

**Comment by vlad88sv** [comment]
Thank you all!!!!
