### ISSUE TITLE
Can't create views on Ubuntu

### ISSUE THREAD

**Issue by PatrickHeneise** [apache/couchdb-pkg#6]
I just installed CouchDB via `snap` on a fresh Ubuntu 17.04 VM. I tried to create views on a db with >5k documents which shouldn't be an issue but ran into a lot of timeouts.

After a while, I tried to create the view on an empty database which didn't work either, and finally ran the verification, says Views don't work.

This is the syslog:

```
Sep 12 16:45:26 bsr-couchdb kernel: [ 2503.848130] audit: type=1400 audit(1505234726.242:41): apparmor="DENIED" operation="capable" profile="snap.couchdb.server" pid=2160 comm="beam" capability=35  capname="wake_alarm"
Sep 12 16:45:26 bsr-couchdb kernel: [ 2504.508119] audit: type=1400 audit(1505234726.902:42): apparmor="DENIED" operation="exec" profile="snap.couchdb.server" name="/bin/df" pid=2216 comm="sh" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
Sep 12 16:46:12 bsr-couchdb kernel: [ 2550.225799] audit: type=1326 audit(1505234772.618:43): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2234 comm="couchjs" exe="/snap/couchdb/1/rel/couchdb/bin/couchjs" sig=31 arch=c000003e syscall=141 compat=0 ip=0x7f43259cdd27 code=0x0
Sep 12 16:49:12 bsr-couchdb kernel: [ 2729.624138] audit: type=1326 audit(1505234952.018:44): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2268 comm="couchjs" exe="/snap/couchdb/1/rel/couchdb/bin/couchjs" sig=31 arch=c000003e syscall=141 compat=0 ip=0x7f877badfd27 code=0x0
```

## Expected Behavior

Views should be created.

## Current Behavior

<img width="709" alt="screen shot 2017-09-12 at 18 40 15" src="https://user-images.githubusercontent.com/74390/30338272-650be380-97eb-11e7-9462-07177740dd20.png">

## Steps to Reproduce (for bugs)
1. `sudo snap install couchdb`
2. Setup single-node system
3. Verify

## Context

Can't use CouchDB without views.

## Your Environment
* Version used: 2.0.0
* Operating System and version (desktop or mobile): Ubuntu 17.04

**Comment by wohali** [comment]
Thanks for the report. Definitely looks like a permissions issue.

I know virtually nothing about the snap packaging setup or approach. @mhall119 do you know what might be wrong?

**Comment by PatrickHeneise** [comment]
I have no idea what AppArmor is. It's a clean/fresh Ubuntu install with Digital Ocean, don't want to run anything else than CouchDB.

**Comment by wohali** [comment]
Then run these commands and it should resolve your problem:

```
sudo service apparmor stop
sudo update-rc.d -f apparmor remove
sudo apt-get remove apparmor apparmor-utils

**Comment by PatrickHeneise** [comment]
Seems `snapd` requires `apparmor` to run:

```
sudo apt-get install snapd
[sudo] password for patrick: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  apparmor
Suggested packages:
  apparmor-profiles apparmor-profiles-extra apparmor-utils
The following NEW packages will be installed:
  apparmor snapd
```

All files in `/var/snap/couchdb` belong to `root` and the couchdb process is also running as root, that should also change, no?

**Comment by PatrickHeneise** [comment]
https://github.com/apache/couchdb/pull/446 seems related.

**Comment by ryanjyoder** [comment]
@PatrickHeneise I think your right. When I added the changes from apache/couchdb#446 it fixed the issues with the view. I'm a bit confused where this snapcraft.yaml file is supposed to reside (couchd or couchdb-pkg?).

I changed this line:
https://github.com/apache/couchdb-pkg/blob/master/snap/snapcraft.yaml#L12
to:
plugs: [network-bind, browser-support, process-control, mount-observe]

And it worked magically. I'd be happy to create a PR for this, but I don't know a lot the security implications of doing this...

**Comment by wohali** [comment]
This is the right repo, we moved the snapfile out of the main repo for various reasons.

Can you test if it works without the browser-support option? If so we can match line 9, which would be ideal.

**Comment by ryanjyoder** [comment]
I get the following error without browser-support. I'm not sure which resources couchjs needs, but it doesn't work without it.

`Dec  2 22:37:54 localhost kernel: [ 1129.519379] audit: type=1326 audit(1512254274.125:84): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=4477 comm="couchjs" exe="/snap/couchdb/x1/rel/couchdb/bin/couchjs" sig=31 arch=40000028 syscall=97 compat=0 ip=0x76c7ec06 code=0x0`

**Comment by ryanjyoder** [comment]
:)
![_20171202_153929](https://user-images.githubusercontent.com/4651456/33520818-2d9a2a76-d777-11e7-840b-7f4ab53ea881.JPG)
