### ISSUE TITLE
CentOS 7 Install dependency error: Requires: mozjs60

### ISSUE THREAD

**Issue by michaelbreslin** [apache/couchdb-pkg#61]
## Expected Behavior
Install on CentOS 7 to work.

## Current Behavior
Went through installation on CentOS 7 machine.

Installed dependencies using http://docs.couchdb.org/en/latest/install/unix.html?highlight=re#redhat-based-fedora-centos-rhel-systems

When running:

`$ sudo yum -y install epel-release && sudo yum -y install couchdb`

Get:

```
Error: Package: couchdb-3.0.0-1.el7.x86_64 (bintray--apache-couchdb-rpm)
           Requires: mozjs60
```

## Your Environment
* Version used: 3.0
* Operating System and version (desktop or mobile): CentOS 7 (3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by wohali** [comment]
Hi @michaelbreslin , 

Whoops. I'll fix this right away.

**Comment by michaelbreslin** [comment]
Thanks @wohali, let me know if you need any more info or want me to test something out.

**Comment by wohali** [comment]
@michaelbreslin New builds for CentOS 6 and 7 up, please check? Thanks.

**Comment by wohali** [comment]
for the record, this was the fix: https://github.com/apache/couchdb-pkg/commit/15613fa0e4380960651ac211d0498cfc57981bc6

**Comment by wohali** [comment]
Closing because I'm fairly certain this is fixed; if not, please poke me and I'll re-open.

**Comment by michaelbreslin** [comment]
Tested it again and no dependency error
