### ISSUE TITLE
openSUSE: Compilation problem (CouchDB 3.0.0, SpiderMonkey 60)

### ISSUE THREAD

**Issue by rolfn** [apache/couchdb-pkg#65]
I tried to compile CouchDB 3.0.0 for openSUSE 15.1 in the following way:
```
sudo zypper install help2man libcurl-devel
make download-couch openSUSE \
URL=http://mirror.23media.de/apache/couchdb/source/3.0.0/apache-couchdb-3.0.0.tar.gz
```
This ends with a successful creation of the rpm file. Note: `make openSUSE` is the same as `make centos7`. In a next step I tried to use "SpiderMonkey 60":
```
sudo zypper install mozjs60 mozjs60-devel
make centos8
```
This ends with the following error:
```
/usr/include/mozjs-60/js-config.h:24:4: error: #error "SpiderMonkey was configured with --enable-debug, so DEBUG must be defined when including this header"
 #  error "SpiderMonkey was configured with --enable-debug, so DEBUG must be defined when including this header"
    ^~~~~
ERROR: compile failed while processing /home/nieprasc/myapps/couchdb/apache-couchdb-3.0.0/src/couch: rebar_abort
make[1]: *** [Makefile:125: couch] Error 1
```
What is the problem here? What can I do? 

Thanks in advance.

**Comment by wohali** [comment]
Looks like this is an upstream bug in openSUSE that's previously been fixed.

Inspecting the changelog inside of http://download.opensuse.org/repositories/mozilla:/Factory/openSUSE_Factory/src/mozjs60-60.9.0-38.1.src.rpm shows me:

```
* Wed May 29 2019 Bjørn Lie <bjorn.lie@gmail.com>
- No longer pass --enable-debug to configure. It is not needed for
  our endusers, and will only slow down the engine. Nor have we
  built it with debug in the past.
```

This appears to have been made 2 changes prior to updating the openSUSE rpm to mozjs 60.9.0. It also brings that RPM in line what what I see from CentOS:

https://git.centos.org/rpms/mozjs60/blob/c8/f/SPECS/mozjs60.spec

and what I see in Debian:

https://sources.debian.org/src/mozjs60/60.8.0-2/debian/rules/

neither of which use the `--enable-debug` flag.

Can you check which version you've downloaded locally? If it's prior to the fix, I don't see any workaround possible, and suggest you stick with SM 1.8.5 until you can update to a version of openSUSE that uses the newer SM60 package.

**Comment by rolfn** [comment]
I use openSUSE’s regular release (15.1). The containing mozjs60 has the version 60.4.0 and is compiled with `--enable-debug`. I will use  SM 1.8.5 until the fixed version is available.

Many thanks for your good analysis.
