### ISSUE TITLE
RPM needs to tag vm.args as a config file

### ISSUE THREAD

**Issue by dholth** [apache/couchdb-pkg#66]
I used `yum update -y` to update my system. This included an upgrade from CouchDB 2 to CouchDB 3, but the upgrade makes the database unusable. I am using a single CouchDB instance on RHEL7. The root database info and _session work, but accessing any database shows

```
error | "internal_server_error"
reason | "No DB shards could be opened."
ref | 2822102114
```

The logs also complain about a `Failed to ensure auth ddoc _users/_design/_auth exists for reason: read_failure`

Could it be related to the RPM upgrade overwriting the cluster settings in `default.ini` because I had not edited this config file?

CouchDB 3.0 setting:
```
[cluster]
q=2
n=3
```

CouchDB 2 setting:
```
[cluster]
q=8
n=3
```

Changing the setting back did not help, neither did reinstalling CouchDB 2.3.1

**Comment by dholth** [comment]
Thanks. I assume the only way to change -name after the fact is to replicate to a new CouchDB?

**Comment by wohali** [comment]
@dholth There is a manual process. You need to edit the internal `/_dbs` database, once per database document, and change all references to the old name to the new one. This is done thru port 5986 (2.x) or the `/_node/<nodename>/_dbs` path.

Test it out on one DB first and confirm that you've got a workable process before you mass update all of them. For a single-node installation, the fix should work immediately for the edited DB.
