### ISSUE TITLE
Alpine Linux apk build

### ISSUE THREAD

**Issue by spaulg** [apache/couchdb-pkg#69]
Alpine Linux Couchdb package that can be installed using the Alpine apk tool

## Expected Behavior
Whilst in Alpine Linux, the apk tool would be used to install a copy of couchdb from a couchdb repository.

## Current Behavior
There is no Alpine package. It must be built from source.

## Possible Solution
An Alpine Linux APKBUILD file to produce an installable apk file. The file would be hosted by couchdb project much like rpms and debs.

## Context
I use Alpine Linux for my CI processes. I use couchdb as part of the solution but its not available as an apk. I'd like a pre-built copy that can be installed by apk to make the CI build as quick as possible.

## Your Environment
I have a beta version of couchdb 3.0.0 building for Alpine 3.11 (older versions of Alpine come with package version/dependency problems). I'd be interested to know if the couchdb project team wanted to take over it.

**Comment by spaulg** [comment]
Also linked to https://github.com/apache/couchdb-docker/issues/156

**Comment by wohali** [comment]
@spaulg Would you be willing to help maintain the file going forward?

And, can you share your current APKBUILD file?

**Comment by spaulg** [comment]
The project is here: https://github.com/spaulg/couchdb-alpine-package
The APKBUILD file is in the project source. An apk build thats produced from it can be downloaded from the latest Github action build.

Happy to maintain going forwards. I'm just not sure how distribution of the build would work - whether couchdb wanted to host their own repo or if I should build my own.

**Comment by wohali** [comment]
First glance, this looks sane.

We'll need to see if we can host a repo over at bintray, where our deb/rpm repos are - let me know if you know anything about this.

I'm in the middle of our 3.0.1/3.1.0 release cycle right now and won't have more time to look at this until a few days from now.

**Comment by spaulg** [comment]
I've no knowledge of bintray but I can learn if need be.

**Comment by olekristensen** [comment]
Any news on this? I am forced to mount persistent storage via cifs using local mounts in compose files at a customer's inhouse RHEL docker swarm setup, and for some reason i can usually make it work on alpine-based images. otherwise it fails with an operation not permitted.

**Comment by wohali** [comment]
@olekristensen No news, but your issue is not anything Alpine-specific. I recommend researching this through Docker forums.

Further, for CouchDB, we have users who have experienced major data loss using persistent storage via CIFS or network mount - this is not a recommended deployment scenario for CouchDB in any regard.

**Comment by big-r81** [comment]
I would close this for now (almost 4 years ago and no updates to the APKBUILD file of the external repo)
