### ISSUE TITLE
How to correctly specify install path for silent Windows install?

### ISSUE THREAD

**Issue by magel20** [apache/couchdb-pkg#71]
## Expected Behavior
I just started using CouchDB and have a question regarding the installation on windows. I followed these instructions: https://docs.couchdb.org/en/stable/install/windows.html#installation-from-binaries and it worked perfectly.
Only thing I did was change the path from the one proposed by the installer (with spaces) to path without spaces.

## Current Behavior
Then I tried the silent installation because this might be relevant for me in the future. Basically this also works except that it installs CouchDB to a path with spaces (The same path the installer would propose): D:/Program Files/Apache CouchDB

What irritates me here is that the installation instructions advises to not use spaces within the path, but the silent installation is doing that anyways. Is there a way to avoid that?

And also for my first minor tests CouchDB seems to work as expected, but I also don't want to run into trouble later on because of that.

## Your Environment
* Version used: 3.1.0
* Browser Name and version: Chrome 78 
* Operating System and version (desktop or mobile): Windows10 1803

**Comment by wohali** [comment]
Try specifying `msiexec /i "path-to-couchdb.msi" 
TARGETDIR="C:\YourPath\" and see if that works. If not it's a bug in 
docs or the code we can fix.

We no longer require you to install to a path with no spaces in 3.x, 
that's a doc bug. PRs welcome.

**Comment by magel20** [comment]
If I try that it installs it to "C:/CouchDB/Program Files/Apache CouchDB" so it just appends the standard path (without the drive) to the passed target directory

I also have one additional question. I tried installing CouchDB not as a windows service and have trouble with starting and stopping it. I used the couchdb.cmd within the bin directory to start it and this works. And stopping it with Ctrl+C works as well. But if I start it and let it run in the background I can only stop it if I kill the process. 

I read somewhere (I don't find where that was anymore) that it is possible to run the couchdb.cmd with parameters like 'restart' or 'stop', but actually my impression is that this script does not care about the arguments I pass or am I just using the wrong ones? Or is there another script to start and stop the db correctly?

**Comment by wohali** [comment]
I'll research the `TARGETDIR` issue and get back to you.

If you don't run CouchDB as a Windows Service your choice is to run `couchdb.cmd` and manually stop it (with `Ctrl+C`) or to use something like the following from an administrative command line - when installing the Service:

```
net start "Apache CouchDB"
net stop "Apache CouchDB"
```

The `couchdb.cmd` file does not accept parameters like `restart` or `stop`, sorry.

**Comment by wohali** [comment]
@magel20 Can you try specifying `APPLICATIONFOLDER` instead of `TARGETDIR` and see if that fixes your problem? Thanks.

**Comment by magel20** [comment]
> If you don't run CouchDB as a Windows Service your choice is to run `couchdb.cmd` and manually stop it (with `Ctrl+C`) or to use something like the following from an administrative command line - when installing the Service:
> 
> The `couchdb.cmd` file does not accept parameters like `restart` or `stop`, sorry.

And I guess other scripts for that purpose do not exist otherwise you would have mentioned it?

> @magel20 Can you try specifying `APPLICATIONFOLDER` instead of `TARGETDIR` and see if that fixes your problem? Thanks.

Using `APPLICATIONFOLDER` does the trick. Thank you!

**Comment by wohali** [comment]
> And I guess other scripts for that purpose do not exist otherwise you would have mentioned it?

Nope, sorry, other than the `net start/stop` commands for the Windows service.

> > @magel20 Can you try specifying `APPLICATIONFOLDER` instead of `TARGETDIR` and see if that fixes your problem? Thanks.
> 
> Using `APPLICATIONFOLDER` does the trick. Thank you!

Great! I'll update the documentation.
