### ISSUE TITLE
Add support for Debian 11 (bullseye)

### ISSUE THREAD

**Issue by sblaisot** [apache/couchdb-pkg#82]
Debian 11 (Bullseye) is released.

Could you please provide couchdb packages for this distribution?

**Comment by wohali** [comment]
Yup, CouchDB 3.2 is imminent, and will include bullseye packages. We won't be going back to rebuild older versions with bullseye support at this time.

**Comment by wohali** [comment]
In fact, the work is done:

https://github.com/apache/couchdb-pkg/commit/cff02c2226249267ec85fad2c5b72b159b9002e4

so this is closing. Look to the main CouchDB project for the 3.2 release.
