### ISSUE TITLE
enable_cors is written to httpd section instead of chttpd

### ISSUE THREAD

**Issue by Napsty** [apache/couchdb-pkg#96]
## Current Behavior
The CouchDB package creates the following file after the installation: `/opt/couchdb/etc/local.d/10-admins.ini`. This also configures to enable CORS by default using `enable_cors = true`. However the package writes this into the `[httpd]` section, whereas the documentation (https://docs.couchdb.org/en/latest/config/http.html#config-cors) states:

> Changed in version 3.2: moved from [httpd] to [chttpd] section

```
root@couchdb:~# cat /opt/couchdb/etc/local.d/10-admins.ini

# Package-introduced administrative user
[admins]
redacted

[chttpd_auth]
secret = redacted

[couchdb]
uuid = redacted

[httpd]
enable_cors = true

[cors]
origins = *
credentials = true
headers = accept, authorization, content-type, origin, referer
methods = GET, PUT, POST, HEAD, DELETE
```

At the same time, `origins = *` and `crecredentials = true` don't work together as mentioned in the documentation:

> You can’t set origins = * and credentials = true option at the same time

Maybe look into this at the same time.

## Expected Behavior
[httpd] section should be called [chttpd] in /opt/couchdb/etc/local.d/10-admins.ini. 

## Possible Solution
Rename [httpd] section to [chttpd] in /opt/couchdb/etc/local.d/10-admins.ini. 

## Your Environment
* Version used: 3.2.2-1~bullseye
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Debian Bullseye
* Link to your project: N/A

**Comment by big-r81** [comment]
Hi Claudio,

was this a complete new install of CouchDB? So no configuration files were present before install?

**Comment by Napsty** [comment]
Yes, this was a brand new install.

**Comment by big-r81** [comment]
Hi, did you use Fauxton to configure CORS.

**Comment by Napsty** [comment]
> Hi, did you use Fauxton to configure CORS.

Yes, this is very possible. I just installed a brand-new CouchDB on a new/empty Bullseye and after the installation of the `couchdb` package, the file `/opt/couchdb/etc/local.d/10-admins.ini` only contains the admin user.

So looks like the cors config in the wrong section was created by Fauxton. Package is therefore clean. Sorry for the noise.
